remove cask dependency
when trying to upgrade on OS X I got

    Error: No available formula with the name "homebrew/cask/aws-vault" (dependency of alphagov/gds/gds-cli)

It seems that it's not possible to depend on casks:
https://discourse.brew.sh/t/how-to-make-formula-depend-on-cask/3557

Maybe we should just put something in the CAVEATS section?