govuk-connect: Use brewed Ruby instead of system Ruby
- On Mojave, system Ruby is 2.3.7 which is too old for govuk-connect.
  The `uses_from_macos` here meant "use system Ruby on macOS, and the
  latest Ruby on Linux" (because Linux doesn't ship with Ruby reliably).
- This meant users were getting the following error:

```
brew upgrade alphagov/gds/govuk-connect
gem
install
--ignore-dependencies
govuk-connect-0.1.0.gem
ERROR:  Error installing govuk-connect-0.1.0.gem:
	govuk-connect requires Ruby version >= 2.5.
```